[env]
CMAKE_C_COMPILER = "clang"
CMAKE_CXX_COMPILER = "clang++"

[tools]
# Build Tools
cmake = "4.3.3"
ninja = "1.13.2"
"github:doxygen/doxygen" = "Release_1_17_0"

# Developer tools
prek = "0.5.2"
"github:cmakefmt/cmakefmt" = "1.6.0"
"github:zizmorcore/zizmor" = "1.25.2"
