name: Build & Test

on:
  - push
  - pull_request

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
          - id: windows-2025-vs2026
            name: Windows
          - id: macos-latest
            name: macOS

    runs-on: ${{ matrix.os.id }}
    name: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0

      - name: configure
        run: cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j $(nproc)

      - name: test
        run: ctest --test-dir build --build-config Debug -j $(nproc) --output-on-failure --output-junit junit.xml

      - name: collect code coverage
        if: ${{ matrix.os.id != 'windows-2025-vs2026' }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          fail_ci_if_error: true

      - name: collect test results
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          fail_ci_if_error: true
